services:
  app:
    build: .
    container_name: app
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - webnet
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - webnet

networks:
  webnet: