services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - webnet
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - webnet
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/conf.d:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot -n --post-hook 'docker exec message-board-nginx-1 nginx -s reload'; sleep 12h; done"
    networks:
      - webnet


networks:
  webnet: