services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - webnet
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - webnet

networks:
  webnet: